/*
* generated by Xtext
*/
package org.xtext.mgpl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MgplDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.mgpl.ui.internal.MgplDSLActivator.getInstance().getInjector("org.xtext.mgpl.MgplDSL");
	}
	
}
