/*
 * generated by Xtext
 */
package org.xtext.mgpl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MgplDSLUiModule extends org.xtext.mgpl.ui.AbstractMgplDSLUiModule {
	public MgplDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
