/*
 * generated by Xtext
 */
package org.xtext.mgpl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.mgpl.ui.internal.MgplDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MgplDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MgplDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MgplDSLActivator.getInstance().getInjector(MgplDSLActivator.ORG_XTEXT_MGPL_MGPLDSL);
	}
	
}
