/*
 * generated by Xtext
 */
package org.xtext.mgpl.ui.contentassist

import org.xtext.mgpl.ui.contentassist.AbstractMgplDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MgplDSLProposalProvider extends AbstractMgplDSLProposalProvider {
}
