/*
* generated by Xtext
*/
package org.xtext.mgpl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.mgpl.services.MgplDSLGrammarAccess;

public class MgplDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MgplDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.mgpl.parser.antlr.internal.InternalMgplDSLParser createParser(XtextTokenStream stream) {
		return new org.xtext.mgpl.parser.antlr.internal.InternalMgplDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MgplDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MgplDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
