/*
* generated by Xtext
*/
package org.xtext.mgpl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MgplDSLStandaloneSetup extends MgplDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new MgplDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

