/**
 * generated by Xtext
 */
package org.xtext.mgpl.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.mgpl.mgplDSL.AttrAss;
import org.xtext.mgpl.validation.AbstractMgplDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MgplDSLValidator extends AbstractMgplDSLValidator {
  @Check
  public void checkSpeed(final AttrAss aa) {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from Class<Disj> to EStructuralFeature");
  }
}
