/**
 * generated by Xtext
 */
package org.xtext.mgpl.validation;

import org.xtext.mgpl.validation.AbstractMgplDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MgplDSLValidator extends AbstractMgplDSLValidator {
}
